### ISSUE TITLE
Context filter

### ISSUE THREAD

**Issue by weedkiller** [danemorgridge/efrepo#6]
Hi, how do we do a context filter, for e.g. I want to filter out information only for this tenantId or company Id for this users session instance scoped from login to log out

thanks

**Comment by danemorgridge** [comment]
The repository has a .Where method that you can use. Something like the following:

`yourRepository.Where(m => m.TenantId == 1)`

**Comment by weedkiller** [comment]
Thanks, I was wondering if this could be set as part of the constructor during a new session in the base class. 

So the generic T4 Templates could have an option to handle the filter, like soft delete and tenants
